secret_word = [
    115, 101, 99, 114, 101, 116, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
]

expected_hash = [
    232, 176, 82, 88, 219, 58, 2, 196,
    38, 209, 159, 212, 58, 38, 134, 214,
    217, 70, 166, 146, 25, 117, 78, 164,
    109, 206, 1, 135, 187, 226, 60, 70,
]