[package]
name = "position_movement"
#name = "trap_grid"
type = "bin"
authors = ["masaun"]

[dependencies]
# @dev - Binary Merkle Root library by zk-kit.noir
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }

# @dev - Poseidon hash function library
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }